### ISSUE TITLE
Adding EOS folder to eic-shell

### ISSUE THREAD

**Issue by michael-pitt** [eic/eic-shell#6]
**Is your feature request related to a problem? Please describe.**
When setting up `eic-shell` on lxplus.cern.ch, the mounted folder `/eos` is removed.

**Describe the solution you'd like**
Add `/eos` to `install.sh` (L186)

**Comment by buddhasystem** [comment]
I'm just curious why eos needs to be mapped specifically on mnt.

**Comment by wdconinc** [comment]
You can map it wherever. The directory needs to exist. /mnt is canonical for mounting external filesystem. That's its sole purpose.
